export const GET_STATES_LIST_REQUEST = 'GET_STATES_LIST_REQUEST';
export const GET_STATES_LIST_SUCCESS = 'GET_STATES_LIST_SUCCESS';
export const GET_STATES_LIST_FAIL = 'GET_STATES_LIST_FAIL';

export const GET_COUNTIES_LIST_REQUEST = 'GET_COUNTIES_LIST_REQUEST';
export const GET_COUNTIES_LIST_SUCCESS = 'GET_COUNTIES_LIST_SUCCESS';
export const GET_COUNTIES_LIST_FAIL = 'GET_COUNTIES_LIST_FAIL';

export const GET_COUNTY_DETAILS_REQUEST = 'GET_COUNTIES_LIST_REQUEST';
export const GET_COUNTY_DETAILS_LIST_SUCCESS = 'GET_COUNTY_DETAILS_LIST_SUCCESS';
export const GET_COUNTY_DETAILS_LIST_FAIL = 'GET_COUNTIES_LIST_FAIL';
